mysite/blog/urls.py
from django.urls import path, re_path
from . import views

app_name = 'blog'
urlpatterns = [
    # url(r'^$',            views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name='post_list'),         # Вариант на Class-based views
    path('',              views.post_list, name='post_list'),         # Вариант на "общих" представлениях (views)

    # url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list, name='post_list_by_tag'),  # теги исходное
    path('tag/<slug:tag_slug>/',        views.post_list, name='post_list_by_tag'),  # теги 1

    # url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$',views.post_detail, name='post_detail'),
    path('blog/<int:year>/<int:month>/<int:day>/<slug:post>/',                 views.post_detail, name='post_detail'),

    # url(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),
    path('blog/<int:post_id>/share/', views.post_share, name='post_share'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
]

mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from taggit.managers import TaggableManager


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.CharField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=(self.publish.year,
                             self.publish.strftime('%m'),
                             self.publish.strftime('%d'),
                             self.slug,
                             ))

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.DO_NOTHING, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

mysite/blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)               # имя читающего пост
    email = forms.EmailField()                          # электронка читающего пост
    to = forms.EmailField()                             # кому отправить рекомендацию
    comments = forms.CharField(required=False,
                              widget=forms.Textarea)    # комментарии в письме


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

mysite/blog/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger    # Для общего представления
from django.views.generic import ListView                                   # Для представления на основе класса
from django.core.mail import send_mail
from django.db.models import Count
from django.shortcuts import render, get_object_or_404
from django.conf import settings
from taggit.models import Tag
from .models import Post, Comment
from .forms import EmailPostForm, CommentForm


class PostListView(ListView):
    # Представление на основе классов
    # queryset = Post.publish.all()     # Так на сайте предлагается фильтровать опубликованные посты
    queryset = Post.objects.filter(status='published')
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_list(request, tag_slug=None):
    # Представление (views) общее
    # posts = Post.objects.all()
    # posts = Post.objects.filter(status='published')
    object_list = Post.objects.filter(status='published')

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)               # 3 поста на странице
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # Если номер страницы не целое число, то поставим первую страницу
        posts = paginator.page(1)
    except EmptyPage:
        # Если страница выскакивает за диапазон - показываем последнюю страницу
        posts = paginator.page(paginator.num_pages)

    return render(request,
                  'blog/post/list.html',
                  {'page': page,
                   'posts': posts,
                   'tag': tag,
                   })


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post,
                             # status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day,
                             slug=post,
                             )
    # Список активных комментов для этого поста
    comments = post.comments.filter(active=True)

    if request.method == 'POST':
        # Комментарий запостили
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Создается объект Comment, но ещё не сохраняется в базу
            new_comment = comment_form.save(commit=False)
            # Назначаем текущий пост для коммента
            new_comment.post = post
            # Сохраняем коммент в базу данных
            new_comment.save()
    else:
        comment_form = CommentForm()

    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    # similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = Post.objects.filter(status='published')
    similar_posts = similar_posts.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]

    return render(request,
                  'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'coment_form': comment_form,
                   'similar_posts': similar_posts,
                    }
                  )


def post_share(request, post_id):
    # Извлечение поста по id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        # Form была отправлена (заполнена и отправлена "submit")
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # если поля Form прошли проверку (valid), то используем "чистые" данные (cleaned_data)
            cd = form.cleaned_data
            # send mail
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommended you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            # send_mail(subject, message, admin@myblog.com, cd['to'])
            send_mail(subject,
                      message,
                      settings.EMAIL_HOST_USER,
                      [cd['to']],
                      fail_silently=False)
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})

mysite/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <title>
            {% block title %}
            {% endblock %}
        </title>
        <link href="{% static "css/blog.css" %}" rel="stylesheet">
        <meta charset="UTF-8">
        <title>Title</title>

        <style>
            p {
                margin-top: 0.5px;
                margin-bottom: 0.1px;
                line-height: 100%;
            }
            .b1 {
                background: #4099ff; /* Синий цвет фона */
                border: #4099ff;
                color: white; /* Белые буквы */
                font: bold italic;
                font-size: 9pt; /* Размер шрифта в пунктах */
                width: 110px;
                height: 30px;
            }

        </style>

    </head>

    <div>
        <div class="main">
            <div id="content">
                {% block content %}
                {% endblock %}
            </div>
        </div>
        <div class="sidenav">
            <div id="sidebar">
<!--                <a href="">
                    <h2>MY BLOG (sidebar, base)</h2>
                </a> -->
                <h2>МОЙ БЛОГ (sidebar, base)</h2>
                <p>Это мой блог.</p>
                <p>Общее количество постов в нём: {% total_posts %} </p>
                <h3>Последние посты:</h3>
                {% show_latest_posts 2 %}
            </div>
        </div>
    </body>

</html>

mysite/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% block title %}
    {{ post.title }}
{% endblock %}
{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
        {{ post.body|linebreaks }}

    <p>
        <a href="{% url 'blog:post_share' post_id=post.pk %}">Share the post</a>
    </p>

    <h2>Подобные посты</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        Подобных постов нет
    {% endfor %}

    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Комментарий {{ forloop.counter }} от {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>Комментариев нет</p>
    {% endfor %}

    {% if new_comment %}
        <h2>Ваш комментарий был успешно добавлен</h2>
    {% else %}
        <h2>Новый комментарий</h2>
        <form action="." method="post">
            {{ coment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Добавить комментарий"></p>
        </form>
    {% endif %}

{% endblock %}

mysite/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

mysite/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% block title %}My blog (title, list){% endblock %}
{% block content %}
    <h1>My blog (content, list)</h1>
    <hr align="left">
    {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}


    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h2>

        <p class="tags">
            Тэги:
            {% for tag in post.tags.all %}
                <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                    {{ tag.name }}
                </a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
<!--            {{ post.tags.all|join:", " }}   -->
        </p>

        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body|truncatewords:30|linebreaks }}
    {% endfor %}

<!--    {% include "pagination.html" with page=page_obj %} -->  <!-- Вариант на Class-based views -->
    {% include "pagination.html" with page=posts %}      <!-- Вариант на "общих" представлениях (views) -->

{% endblock %}

mysite/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}Share a post{% endblock %}
{% block content %}
    {% if sent %}
        <h1>E-mail succesfully sent</h1>
        <p>
            "{{ post.title }}" was succesfully sent to {{ cd.to }}.
        </p>
    {% else %}
        <h1>Поделитесь постом "{{ post.title }}" по электронке</h1>
        <form action="." method="post">
            {{ form.as_p }}
<!--
            {% for field in form %}
                <div>
                    {{ field.errors }}
                    {{ field.label_tag }}
                    {{ field }}
                </div>
            {% endfor %}
-->


            {% csrf_token %}
            <input type="submit" class="b1" value="SEND E-MAIL">
        </form>
    {% endif %}

{% endblock %}

mysite/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>